job_analysis_and_personalization_task:
  description: >
    Create a fully customized cover letter body based on **{job_offer_details}** and **{candidate_cv}**.

    **Requirements:**
    - Write the letter in the language of the job offer.
    - Use appropriate formal language without any placeholders or generic phrases.
    - Follow the structure below:

    1) **Greeting:** Start with "Madame, Monsieur" in the language of the job offer.
    2) **Introduction:** Motivation for applying and unique qualifications.
    3) **Skills and Experience:** Relevant skills and experiences aligned with the job offer.
    4) **Motivation and Future Contributions:** Enthusiasm and how the candidate can add value.
    5) **Conclusion:** End with a traditional Swiss closing phrase, such as "Je vous prie d'agréer, Madame, Monsieur, l'expression de mes salutations distinguées," or the equivalent in the job offer's language.

  expected_output: >
    A tailored cover letter in the language of the job offer, between 250 and 350 words. that maximizes the candidate's chances of securing an interview without introducing false information, without an opening subject line or final signature, adhering to the provided structure and guidelines.
  agent: job_analyst_and_personalization_writer

optimal_recipient_task:
  description: >
    Generate an optimal recipient and subject line for a cover letter, specifically tailored to maximize the chances of success for the job application. Use details from the job offer to inform your choice.

    Job Offer Details: {job_offer_details}

    The recipient information should be concise, formatted between 2 to 4 lines, with each line no longer than 20 characters. Ensure each line is as impactful as possible.

  expected_output: >
    A subject line and recipient information that are optimized for a cover letter, designed to maximize the chances of success for the job application.

  agent: info_extraction_and_formatting_specialist






