###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml-py
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off
from typing import Any, Dict, List, Optional, TypeVar, Union, TypedDict, Type, Literal, cast
from typing_extensions import NotRequired
import pprint

import baml_py
from pydantic import BaseModel, ValidationError, create_model

from . import partial_types, types
from .types import Checked, Check
from .type_builder import TypeBuilder
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_CTX, DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME


OutputType = TypeVar('OutputType')


# Define the TypedDict with optional parameters having default values
class BamlCallOptions(TypedDict, total=False):
    tb: NotRequired[TypeBuilder]
    client_registry: NotRequired[baml_py.baml_py.ClientRegistry]
    collector: NotRequired[Union[baml_py.baml_py.Collector, List[baml_py.baml_py.Collector]]]
class BamlAsyncClient:
    __runtime: baml_py.BamlRuntime
    __ctx_manager: baml_py.BamlCtxManager
    __stream_client: "BamlStreamClient"

    def __init__(self, runtime: baml_py.BamlRuntime, ctx_manager: baml_py.BamlCtxManager):
      self.__runtime = runtime
      self.__ctx_manager = ctx_manager
      self.__stream_client = BamlStreamClient(self.__runtime, self.__ctx_manager)

    @property
    def stream(self):
      return self.__stream_client


    
    async def ExtractJobOffer(
        self,
        webpage_text: str,
        baml_options: BamlCallOptions = {},
    ) -> types.JobOfferStructure:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)
      collector = baml_options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = await self.__runtime.call_function(
        "ExtractJobOffer",
        {
          "webpage_text": webpage_text,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )
      return cast(types.JobOfferStructure, raw.cast_to(types, types, partial_types, False))
    
    async def GenerateCoverLetter(
        self,
        user_profile: str,job_description: str,reference_letter: Optional[str],
        baml_options: BamlCallOptions = {},
    ) -> types.CoverLetterBody:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)
      collector = baml_options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = await self.__runtime.call_function(
        "GenerateCoverLetter",
        {
          "user_profile": user_profile,"job_description": job_description,"reference_letter": reference_letter,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )
      return cast(types.CoverLetterBody, raw.cast_to(types, types, partial_types, False))
    
    async def GenerateCoverRecipient(
        self,
        job_description: str,
        baml_options: BamlCallOptions = {},
    ) -> types.CoverLetterRecipient:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)
      collector = baml_options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = await self.__runtime.call_function(
        "GenerateCoverRecipient",
        {
          "job_description": job_description,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )
      return cast(types.CoverLetterRecipient, raw.cast_to(types, types, partial_types, False))
    
    async def RegenerateText(
        self,
        original_text: str,selected_text: str,user_profile: Optional[str],job_description: Optional[str],user_feedback: Optional[str],
        baml_options: BamlCallOptions = {},
    ) -> types.RegeneratedText:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)
      collector = baml_options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = await self.__runtime.call_function(
        "RegenerateText",
        {
          "original_text": original_text,"selected_text": selected_text,"user_profile": user_profile,"job_description": job_description,"user_feedback": user_feedback,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )
      return cast(types.RegeneratedText, raw.cast_to(types, types, partial_types, False))
    


class BamlStreamClient:
    __runtime: baml_py.BamlRuntime
    __ctx_manager: baml_py.BamlCtxManager

    def __init__(self, runtime: baml_py.BamlRuntime, ctx_manager: baml_py.BamlCtxManager):
      self.__runtime = runtime
      self.__ctx_manager = ctx_manager

    
    def ExtractJobOffer(
        self,
        webpage_text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[partial_types.JobOfferStructure, types.JobOfferStructure]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)
      collector = baml_options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = self.__runtime.stream_function(
        "ExtractJobOffer",
        {
          "webpage_text": webpage_text,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )

      return baml_py.BamlStream[partial_types.JobOfferStructure, types.JobOfferStructure](
        raw,
        lambda x: cast(partial_types.JobOfferStructure, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.JobOfferStructure, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def GenerateCoverLetter(
        self,
        user_profile: str,job_description: str,reference_letter: Optional[str],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[partial_types.CoverLetterBody, types.CoverLetterBody]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)
      collector = baml_options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = self.__runtime.stream_function(
        "GenerateCoverLetter",
        {
          "user_profile": user_profile,
          "job_description": job_description,
          "reference_letter": reference_letter,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )

      return baml_py.BamlStream[partial_types.CoverLetterBody, types.CoverLetterBody](
        raw,
        lambda x: cast(partial_types.CoverLetterBody, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.CoverLetterBody, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def GenerateCoverRecipient(
        self,
        job_description: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[partial_types.CoverLetterRecipient, types.CoverLetterRecipient]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)
      collector = baml_options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = self.__runtime.stream_function(
        "GenerateCoverRecipient",
        {
          "job_description": job_description,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )

      return baml_py.BamlStream[partial_types.CoverLetterRecipient, types.CoverLetterRecipient](
        raw,
        lambda x: cast(partial_types.CoverLetterRecipient, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.CoverLetterRecipient, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def RegenerateText(
        self,
        original_text: str,selected_text: str,user_profile: Optional[str],job_description: Optional[str],user_feedback: Optional[str],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[partial_types.RegeneratedText, types.RegeneratedText]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)
      collector = baml_options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = self.__runtime.stream_function(
        "RegenerateText",
        {
          "original_text": original_text,
          "selected_text": selected_text,
          "user_profile": user_profile,
          "job_description": job_description,
          "user_feedback": user_feedback,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )

      return baml_py.BamlStream[partial_types.RegeneratedText, types.RegeneratedText](
        raw,
        lambda x: cast(partial_types.RegeneratedText, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.RegeneratedText, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    

b = BamlAsyncClient(DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME, DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_CTX)

__all__ = ["b"]