###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml-py
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off
import baml_py
from enum import Enum
from pydantic import BaseModel, ConfigDict
from typing import Dict, Generic, List, Optional, TypeVar, Union, Literal

from . import types
from .types import Checked, Check

###############################################################################
#
#  These types are used for streaming, for when an instance of a type
#  is still being built up and any of its fields is not yet fully available.
#
###############################################################################

T = TypeVar('T')
class StreamState(BaseModel, Generic[T]):
    value: T
    state: Literal["Pending", "Incomplete", "Complete"]


class CoverLetterBody(BaseModel):
    subject: Optional[str] = None
    greeting: Optional[str] = None
    introduction: Optional[str] = None
    skills_experience: Optional[str] = None
    motivation: Optional[str] = None
    conclusion: Optional[str] = None
    closing: Optional[str] = None

class CoverLetterRecipient(BaseModel):
    company_name: Optional[str] = None
    recipient_name: Optional[str] = None
    generic_greeting: Optional[str] = None
    address_lines: Optional[List[str]] = None

class JobOfferStructure(BaseModel):
    company_name: Optional[str] = None
    job_title: Optional[str] = None
    location: Optional[str] = None
    job_type: Optional[str] = None
    company_description: Optional[str] = None
    job_description: Optional[str] = None
    responsibilities: Optional[str] = None
    requirements: Optional[str] = None
    benefits: Optional[str] = None
    salary_range: Optional[str] = None
    application_deadline: Optional[str] = None
    contact_info: Optional[str] = None
    application_instructions: Optional[str] = None
    additional_info: Optional[str] = None

class RegeneratedText(BaseModel):
    regenerated_text: Optional[str] = None
