###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml-py
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off
import baml_py
from enum import Enum
from pydantic import BaseModel, ConfigDict
from typing_extensions import TypeAlias
from typing import Dict, Generic, List, Literal, Optional, TypeVar, Union


T = TypeVar('T')
CheckName = TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str

class Checked(BaseModel, Generic[T,CheckName]):
    value: T
    checks: Dict[CheckName, Check]

def get_checks(checks: Dict[CheckName, Check]) -> List[Check]:
    return list(checks.values())

def all_succeeded(checks: Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))



class CoverLetterBody(BaseModel):
    subject: str
    greeting: str
    introduction: str
    skills_experience: str
    motivation: str
    conclusion: str
    closing: str

class CoverLetterRecipient(BaseModel):
    company_name: Optional[str] = None
    recipient_name: Optional[str] = None
    generic_greeting: Optional[str] = None
    address_lines: Optional[List[str]] = None

class JobOfferStructure(BaseModel):
    company_name: Optional[str] = None
    job_title: str
    location: Optional[str] = None
    job_type: Optional[str] = None
    company_description: Optional[str] = None
    job_description: Optional[str] = None
    responsibilities: str
    requirements: str
    benefits: Optional[str] = None
    salary_range: Optional[str] = None
    application_deadline: Optional[str] = None
    contact_info: Optional[str] = None
    application_instructions: Optional[str] = None
    additional_info: Optional[str] = None

class RegeneratedText(BaseModel):
    regenerated_text: str
